### ISSUE TITLE
Documentation -  background image resolution 

### ISSUE THREAD

**Issue by nwies** [ecoAPM/WiFiSurveyor#397]
Hello,

Could it be possible to write on the documentation/Readme the picture maximal size?
Thanks for your update. 
Br

**Comment by SteveDesmond-ca** [comment]
Ooh, that's interesting -- my understanding is that would be based on the browser. Is there a specific image you're having issues with?

**Comment by nwies** [comment]
Sorry,  I missed the details :
I'm working with the latest release for windows.
The image (an error from my side 16000x...  Pixels) I tried to load was not resized and some part of it weren't visible.

**Comment by SteveDesmond-ca** [comment]
Which browser? What's the height of the image? What sort of distortion are you seeing? A screenshot would be great, but understandable if it contains private info.

**Comment by nwies** [comment]
Hello,
I'm working with Chrome.
On the error,  the bottom right corner were not visible. 

I made another try, without being able to reproduce the error. ;) 
I scale my picture from 1280x720 to 23040x12960 and each time the picture showed perfectly.

Thanks for your time. We can close this issue.
