### ISSUE TITLE
No signal on load file

### ISSUE THREAD

**Issue by antoine-helbert-wiztivi** [ecoAPM/WiFiSurveyor#588]
I tried to save, quit and load (on Windows) and there is no signal on all reading point ?
Have i missed something ?
Regards

**Comment by SteveDesmond-ca** [comment]
Hi Antoine, thanks for this report. Could you share the JSON file that was saved? Feel free to redact the SSID names if desired, and replace them with pseudonyms.

**Comment by antoine-helbert-wiztivi** [comment]
Please find this below.
Thx

[TEST4.json.txt](https://github.com/ecoAPM/WiFiSurveyor/files/10086470/TEST4.json.txt)

**Comment by SteveDesmond-ca** [comment]
Thanks again for the quick response. I just confirmed that this bug was introduced in v1.1.0, which was released last month. A new v1.1.1 with the fix will likely be released tomorrow, but in the meantime you can use v1.0.0, as long as you don't need the channel info in the debug panel.

**Comment by SteveDesmond-ca** [comment]
Fixed in v1.1.1
